spring.application.name=accident-scatch-management

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/accident_scene_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

roadwatch.ai-service.url=http://localhost:5000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
axon.axonserver.enabled=false
spring.jpa.open-in-view=false

axon.serializer.general=jackson
axon.serializer.events=jackson
axon.serializer.messages=jackson

spring.kafka.bootstrap-servers=localhost:9092
logging.level.com.example.accidentscatchmanagement.client=DEBUG
spring.cloud.openfeign.circuitbreaker.enabled=true
